//
// Created by creeper on 12/3/24.
//

#ifndef CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_DOMINATION_TREE_H
#define CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_DOMINATION_TREE_H
namespace llvm {

struct DominatorTree {


};

}
#endif //CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_DOMINATION_TREE_H
