//
// Created by creeper on 10/2/24.
//

#ifndef CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_GLOBAL_VARIABLE_H
#define CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_GLOBAL_VARIABLE_H
namespace llvm {

struct GlobalVariable {

};

}
#endif //CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_GLOBAL_VARIABLE_H
