//
// Created by creeper on 9/27/24.
//

#ifndef CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_PASS_H
#define CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_PASS_H
namespace llvm {

}
#endif //CACTRIE_CHIISAI_LLVM_INCLUDE_CHIISAI_LLVM_PASS_H
